#version 430 core

layout (local_size_x = 10, local_size_y = 10, local_size_z = 1) in;

// ----------------------------------------------------------------------------
//
// uniforms
//
// ----------------------------------------------------------------------------

layout(rgba32f, binding = 0) uniform image2D imgOutput;

// ----------------------------------------------------------------------------
//
// functions
//
// ----------------------------------------------------------------------------

void main() {
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);

    // Set color to orange
    vec4 value = vec4(1.0, 0.5, 0.0, 1.0); // Orange color
    imageStore(imgOutput, texelCoord, value);
}
