#version 430 core
layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

// ----------------------------------------------------------------------------
//
// uniforms
//
// ----------------------------------------------------------------------------

layout(rgba32f, binding = 1) uniform image2D imgOutput;
layout(binding = 0) uniform sampler2D tex;

// ----------------------------------------------------------------------------
//
// functions
//
// ----------------------------------------------------------------------------

void main() {
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);

    // Ensure the texelCoord is within bounds
    ivec2 texSize = textureSize(tex, 0);
    if (texelCoord.x >= texSize.x || texelCoord.y >= texSize.y) {
        return;
    }

    // Fetch the texel color from the input texture
    vec4 color = texelFetch(tex, texelCoord, 0);

    // Write the texel color to the output image
    imageStore(imgOutput, texelCoord, color);
}
